version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      -./frontend:/app
    networks:
      - yoursport_network

  authapp:
    build: ./backend/authapp
    command: python manage.py runserver
    volumes:
      - ./backend/authapp:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    networks:
      - yoursport_network


volumes:
  postgres_data:

networks:
  yoursport_network:
    driver: bridge
