
services:
  auth:
    container_name: authentication
    build: ./srcs/backend/AUTH
    image: authimg
    init: true
    networks:
      - net
    env_file:
      - .env
  
  nginx:
    container_name: nginx
    build: ./srcs/reverse_proxy
    image: nginximg
    ports:
      - '21212:80'
    depends_on:
      - auth
    init: true
    networks:
      - net

networks:
  net:
    name: yoursport_network