# Generated by Django 5.1.6 on 2025-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokens_db',
            fields=[
                ('access_token', models.CharField(max_length=10000, unique=True)),
                ('refresh_token', models.CharField(max_length=10000, unique=True)),
                ('identity', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
