# Generated by Django 5.1.6 on 2025-02-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('usermail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('activate', models.BooleanField(default=False)),
            ],
        ),
    ]
